### ISSUE TITLE
H5 端无法打开首页

### ISSUE THREAD

**Issue by aboutZZ** [yudaocode/yudao-mall-uniapp#1]
目标平台H5 开发时商城首页无法打开，控制台报错：
```
来源为“http://localhost:3000/sheep/ui/su-popup/keypress.js”的模块加载失败。 [localhost:3000:21:57](http://localhost:3000/#/)
来源为“http://localhost:3000/uni_modules/uni-transition/components/uni-transition/uni-transition.vue”的模块加载失败。 [localhost:3000:21:57](http://localhost:3000/#/)
来源为“http://localhost:3000/sheep/ui/su-popup/su-popup.vue?vue&type=style&index=0&scoped=f2bacd7c&lang.scss”的模块加载失败。 [localhost:3000:21:57](http://localhost:3000/#/)
GET

AppOnError: TypeError: error loading dynamically imported module: http://localhost:3000/pages/index/index.vue?t=1704858040401
```

目标平台为小程序 开发时，商城首页正常打开。

**Comment by VincentZhangy** [comment]
这是啥，你是不是发错了




vlor
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yudaocode/yudao-mall-uniapp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月10日(星期三) 下午2:12
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[yudaocode/yudao-mall-uniapp] H5 端无法打开首页 (Issue #1)





 
目标平台H5 开发时商城首页无法打开，控制台报错：
 来源为“http://localhost:3000/sheep/ui/su-popup/keypress.js”的模块加载失败。 [localhost:3000:21:57](http://localhost:3000/#/) 来源为“http://localhost:3000/uni_modules/uni-transition/components/uni-transition/uni-transition.vue”的模块加载失败。 [localhost:3000:21:57](http://localhost:3000/#/) 来源为“http://localhost:3000/sheep/ui/su-popup/su-popup.vue?vue&amp;type=style&amp;index=0&amp;scoped=f2bacd7c&amp;lang.scss”的模块加载失败。 [localhost:3000:21:57](http://localhost:3000/#/) GET AppOnError: TypeError: error loading dynamically imported module: http://localhost:3000/pages/index/index.vue?t=1704858040401  
目标平台为小程序 开发时，商城首页正常打开。

**Comment by aboutZZ** [comment]
? H5商城你能打开？

**Comment by YunaiV** [comment]
暂时没碰到

https://doc.iocoder.cn/mall/build/ 参考启动
