### ISSUE TITLE
能否增加一个多商家/商户入驻的功能？

### ISSUE THREAD

**Issue by lfglfg11** [yudaocode/yudao-mall-uniapp#14]
批发、多商户入驻是不是可以考虑下啊

**Comment by lfglfg11** [comment]
还有商城的会员登录，是否可以增加邮箱登录？然后商城会员后台貌似无法增删，也无法对会员改密码。如果会员手机号不用了的话改密码就会很麻烦了，没有渠道改，后台也改不了，因为数据库密码加密，还无法从数据库里进行改动

**Comment by YunaiV** [comment]
暂时还没这个计划。

定位目前是多租户商城。进驻可以按需定制。
