### ISSUE TITLE
访问 /app-api/ 的接口会报426  Upgrade Required

### ISSUE THREAD

**Issue by OnceCrazyer** [yudaocode/yudao-mall-uniapp#15]
<img width="475" alt="image" src="https://github.com/user-attachments/assets/43913618-6bf5-45af-9375-ce0cd31a99cb">
所有/app-api/ 接口 都会报上面的错误，但是admin-api就不会，这是什么问题导致的？如何解决

**Comment by YunaiV** [comment]
kill 下 48080 端口
可能被别的占用了。

然后重启下，就 ok 了。

**Comment by uniquejava** [comment]
> kill 下 48080 端口 可能被别的占用了。
> 
> 然后重启下，就 ok 了。

好用.
