### ISSUE TITLE
小程序真机调试，搜索栏遮挡

### ISSUE THREAD

**Issue by tianbocheng** [yudaocode/yudao-mall-uniapp#5]
- 如下图所示
- 搜索栏被   刘海  遮挡 （部分机型有刘海屏）
![IMG_6149](https://github.com/yudaocode/yudao-mall-uniapp/assets/20829408/4140d743-3648-4632-9339-29e425998712)

**Comment by YunaiV** [comment]
统一放到 https://gitee.com/yudaocode/yudao-mall-uniapp/issues/I8XQZX 跟进哈。
