### ISSUE TITLE
求解决！！！运行到微信或者支付宝开发者工具报错：找不到app.json文件怎么办？

### ISSUE THREAD

**Issue by pwyGouxiong** [yudaocode/yudao-mall-uniapp#7]
如题......
![image](https://github.com/yudaocode/yudao-mall-uniapp/assets/26954826/6e93a220-8086-49aa-86b7-27820bb5e14f)

**Comment by zhengzhiwu2009** [comment]
启动后首页加载不正常啊，底部导航栏都没有
/
![微信截图_20240605181220](https://github.com/yudaocode/yudao-mall-uniapp/assets/35989383/44476b6a-08df-435e-ac4d-af91398c5db3)

**Comment by YunaiV** [comment]
暂时没碰到，建议自查下。。。
