### ISSUE TITLE
分类页面的代码好像跟演示网址的实现不符？

### ISSUE THREAD

**Issue by Brunofan** [yudaocode/yudao-mall-uniapp#9]
演示网站是http://mall.yudao.iocoder.cn/static/html/pc.html          分类的右边是可以显示全部分类的，并且左边跟随右边位置联动。    

代码是https://github.com/yudaocode/yudao-mall-uniapp/blob/master/pages/index/category.vue         分类还是老式的，右边不能显示所有分类，并且左边不能跟着联动。

底部tabbar的分类菜单

**Comment by YunaiV** [comment]
演示是 vue2，最新代码是 vue3.以最新代码为准哈。

不建议使用 vue2

**Comment by Brunofan** [comment]
那为啥vue3的分类页面不是左右联动的？
